### ISSUE TITLE
Je ne peux ajouter le composant "texte et appel à l'action" qu'à l'intérieur d'un bloc multi-colonne, je ne peux pas le faire dans le body

### ISSUE THREAD

**Issue by gauthierna** [betagouv/content-manager#18]
Voici les choix que j'ai dans "body" :
<img width="660" alt="Screenshot 2023-04-12 at 21 19 52" src="https://user-images.githubusercontent.com/12137665/231562759-9e989136-cd35-4c90-9e20-71e76e944e0c.png">

Voici les choix que j'ai dans "multi-colonne" : 
<img width="603" alt="Screenshot 2023-04-12 at 21 19 35" src="https://user-images.githubusercontent.com/12137665/231562714-0a208819-4bf2-4b23-a842-d70ba9913270.png">

**Comment by SebastienReuiller** [comment]
Oui, je me suis fait la réflexion, mais au final, je me suis dit que dans les plupart des cas, nous utilisons ce bloc dans un contexte multicolonne. Et par ailleurs, les blocs qui sont en dehors du multicolonne sont en réalité intégré dans une colonne qui fait toute la largeur, c'est la logique du système de colonne. En conclusion, je pense même qu'il faudrait enlever d'autres blocs qui ne devraient être dispo que dans le multicolonne..

**Comment by gauthierna** [comment]
Je pense qu'il faudra avoir un débat à avoir sur cette histoire du multi-colonne, c'est quand même la porte ouverte à toutes les fenêtres pour qu'un contributeur non-averti fasse n'importe quoi ;)

**Comment by gauthierna** [comment]
Désolé, j'ai répondu trop tard.

Niveau "utilisateur", c'est bizarre, si je veux un bloc "texte et appel à l'action", déjà je ne le trouve pas dans les blocs classiques (frustration car je pense que cela n'existe même pas) et ensuite cela veut dire que je dois faire un bloc multicolonne dans lequel je ne fais qu'une colonne (bizarre en terme de compréhension).

Aujourd'hui le seul bloc "appel à l'action" disponible direct dans le body est celui qui demande une image, et je n'en ai pas forcément besoin
