### ISSUE TITLE
Ajouter la possibilité d'injecter du code custom

### ISSUE THREAD

**Issue by cmarcoin** [betagouv/content-manager#31]
De nombreux outils, notamment des outils de tracking comme Matomo, requièrent l'ajout un snippet de code à un endroit précis dans le code, par exemple : Sur l'ensemble des pages, juste avant la balise `</head>`.

Ce serait top d'avoir la possibilité d'ajouter ces snippets depuis l'interface du CMS.

**Comment by damienlethiec** [comment]
@SebastienReuiller C'est un sujet que vous avez en tête ? :)

**Comment by SebastienReuiller** [comment]
Merci pour la remontée du besoin. Ça a été fait ici : https://github.com/betagouv/content-manager/pull/33
