### ISSUE TITLE
Start with Docker

### ISSUE THREAD

**Issue by cdugeai** [betagouv/content-manager#6]
J'ai essayé de lancer le projet à l'aide de Docker, mais j'ai une erreur Python sur un module qui ne fonctionnerait pas.

J'ai bien copié le `.env.example` vers `.env` mais je ne sais pas si j'ai manqué d'autres étapes.

Merci !

![image](https://user-images.githubusercontent.com/46027833/216583750-58944a85-19c6-41d6-9591-db841b0e3917.png)

**Comment by SebastienReuiller** [comment]
Bonjour @cdugeai , merci pour votre retour. Le storage a été ajouté récemment, mais `django-storage` est bien dans les dépendances. Alors, est-ce que vous pouvez tenter de rebuild avec la commande `docker-compose up --build`  ?

**Comment by cdugeai** [comment]
Merci. Avec cette solution, je bloque à la step 15

![image](https://user-images.githubusercontent.com/46027833/2172
[build_log.txt](https://github.com/betagouv/content-manager/files/10675932/build_log.txt)
70781-65a6f3f8-552e-4a92-b1c3-45a9568f2200.png)

**Comment by SebastienReuiller** [comment]
C'est une bonne nouvelle ! Ici, il vous manque une clé secrète. Dans le fichier `.env`, vous devez avoir la variable `SECRET_KEY=` que je vous invite à compléter par ce que vous voulez. Si c'est un environnement local de test, vous pouvez mettre une clé très simple comme par exemple `SECRET_KEY=maclesecrete`.

**Comment by cdugeai** [comment]
Cela fonctionne bien !
